### ISSUE TITLE
No module named 'mythril.ether' warning in ethereum-dasm-0.1.4

### ISSUE THREAD

**Issue by moatftw** [tintinweb/ethereum-dasm#19]
After installing from using pip3 install ethereum-dasm, I always get this warning:
Symbolic Execution not available: No module named 'mythril.ether'

**Comment by tintinweb** [comment]
hi @moatftw,

mythril's api might have changed in the meantime. did you install with `python3 -m pip install ethereum-dasm[mythril,abidecoder]` ?

cheers,
tin

**Comment by moatftw** [comment]
Yeah I have installed that already.
But still getting this:
>python3 -m ethereum_dasm
Symbolic Execution not available: No module named 'mythril.ether'

**Comment by luolixuan** [comment]
same problem.
When I try to execute: ethereumetl export_geth_traces --start-block 0 --end-block 500000 --provider-uri ~/Library/Ethereum/geth.ipc --batch-size 100 --output geth_traces.json

it shows up the error: Symbolic Execution not available: No module named 'mythril.ether'

I also did the command line mentioned above, but still this error. 
Looking for help, please.

**Comment by tintinweb** [comment]
Hi @moatftw @luolixuan,

thanks for the bug report.
I've fixed an issue due to api change on mythril side. make sure to install the extras `python3 -m pip install ethereum-dasm[mythril,abidecoder]`

please install from the repository in the meantime until I've published the changes to pip with a new version.

cheers,
tin
